/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model;

import edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.*;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrol
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrol.Answer
	 */
	public static final Answer ANSWER = Answer.ANSWER;

	/**
	 * The table crowdcontrol.Constraint
	 */
	public static final Constraint CONSTRAINT = Constraint.CONSTRAINT;

	/**
	 * The table crowdcontrol.Experiment
	 */
	public static final Experiment EXPERIMENT = Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrol.ExperimentsPopulation
	 */
	public static final Experimentspopulation EXPERIMENTSPOPULATION = Experimentspopulation.EXPERIMENTSPOPULATION;

	/**
	 * The table crowdcontrol.GiftCode
	 */
	public static final Giftcode GIFTCODE = Giftcode.GIFTCODE;

	/**
	 * The table crowdcontrol.Notification
	 */
	public static final Notification NOTIFICATION = Notification.NOTIFICATION;

	/**
	 * The table crowdcontrol.Payment
	 */
	public static final Payment PAYMENT = Payment.PAYMENT;

	/**
	 * The table crowdcontrol.Platform
	 */
	public static final Platform PLATFORM = Platform.PLATFORM;

	/**
	 * The table crowdcontrol.Population
	 */
	public static final Population POPULATION = Population.POPULATION;

	/**
	 * The table crowdcontrol.PopulationAnswerOption
	 */
	public static final Populationansweroption POPULATIONANSWEROPTION = Populationansweroption.POPULATIONANSWEROPTION;

	/**
	 * The table crowdcontrol.PopulationResult
	 */
	public static final Populationresult POPULATIONRESULT = Populationresult.POPULATIONRESULT;

	/**
	 * The table crowdcontrol.Rating
	 */
	public static final Rating RATING = Rating.RATING;

	/**
	 * The table crowdcontrol.Tag
	 */
	public static final Tag TAG = Tag.TAG;

	/**
	 * The table crowdcontrol.Task
	 */
	public static final Task TASK = Task.TASK;

	/**
	 * The table crowdcontrol.Template
	 */
	public static final Template TEMPLATE = Template.TEMPLATE;

	/**
	 * The table crowdcontrol.Worker
	 */
	public static final Worker WORKER = Worker.WORKER;
}
