// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email_answer.proto

package edu.kit.ipd.crowdcontrol.workerservice.proto;

public interface EmailAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.EmailAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string authorization = 1;</code>
   */
  java.lang.String getAuthorization();
  /**
   * <code>optional string authorization = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorizationBytes();
}
