// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emailanswer.proto

package edu.kit.ipd.crowdcontrol.workerservice.proto;

public final class Emailanswer {
  private Emailanswer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:crowdcontrol.Email)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 workerID = 1;</code>
     */
    int getWorkerID();
  }
  /**
   * Protobuf type {@code crowdcontrol.Email}
   */
  public  static final class Email extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:crowdcontrol.Email)
      EmailOrBuilder {
    // Use Email.newBuilder() to construct.
    private Email(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Email() {
      workerID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Email(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              workerID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Emailanswer.internal_static_crowdcontrol_Email_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Emailanswer.internal_static_crowdcontrol_Email_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Emailanswer.Email.class, Emailanswer.Email.Builder.class);
    }

    public static final int WORKERID_FIELD_NUMBER = 1;
    private int workerID_;
    /**
     * <code>optional int32 workerID = 1;</code>
     */
    public int getWorkerID() {
      return workerID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (workerID_ != 0) {
        output.writeInt32(1, workerID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (workerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, workerID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Emailanswer.Email parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Emailanswer.Email parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Emailanswer.Email parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Emailanswer.Email parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Emailanswer.Email parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Emailanswer.Email parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Emailanswer.Email parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Emailanswer.Email parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Emailanswer.Email parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Emailanswer.Email parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Emailanswer.Email prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code crowdcontrol.Email}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crowdcontrol.Email)
        Emailanswer.EmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Emailanswer.internal_static_crowdcontrol_Email_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Emailanswer.internal_static_crowdcontrol_Email_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Emailanswer.Email.class, Emailanswer.Email.Builder.class);
      }

      // Construct using edu.ipd.kit.crowdcontrol.workerservice.proto.Emailanswer.Email.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        workerID_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Emailanswer.internal_static_crowdcontrol_Email_descriptor;
      }

      public Emailanswer.Email getDefaultInstanceForType() {
        return Emailanswer.Email.getDefaultInstance();
      }

      public Emailanswer.Email build() {
        Emailanswer.Email result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Emailanswer.Email buildPartial() {
        Emailanswer.Email result = new Emailanswer.Email(this);
        result.workerID_ = workerID_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Emailanswer.Email) {
          return mergeFrom((Emailanswer.Email)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Emailanswer.Email other) {
        if (other == Emailanswer.Email.getDefaultInstance()) return this;
        if (other.getWorkerID() != 0) {
          setWorkerID(other.getWorkerID());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Emailanswer.Email parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Emailanswer.Email) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int workerID_ ;
      /**
       * <code>optional int32 workerID = 1;</code>
       */
      public int getWorkerID() {
        return workerID_;
      }
      /**
       * <code>optional int32 workerID = 1;</code>
       */
      public Builder setWorkerID(int value) {
        
        workerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 workerID = 1;</code>
       */
      public Builder clearWorkerID() {
        
        workerID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:crowdcontrol.Email)
    }

    // @@protoc_insertion_point(class_scope:crowdcontrol.Email)
    private static final Emailanswer.Email DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Emailanswer.Email();
    }

    public static Emailanswer.Email getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Email>
        PARSER = new com.google.protobuf.AbstractParser<Email>() {
      public Email parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Email(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Email> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Email> getParserForType() {
      return PARSER;
    }

    public Emailanswer.Email getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Email_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Email_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021emailanswer.proto\022\014crowdcontrol\"\031\n\005Ema" +
      "il\022\020\n\010workerID\030\001 \001(\005B.\n,edu.ipd.kit.crow" +
      "dcontrol.workerservice.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crowdcontrol_Email_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crowdcontrol_Email_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Email_descriptor,
        new java.lang.String[] { "WorkerID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
