// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workerservice/email_answer.proto

package edu.kit.ipd.crowdcontrol.workerservice.proto;

public final class EmailAnswerOuterClass {
  private EmailAnswerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_EmailAnswer_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_EmailAnswer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n workerservice/email_answer.proto\022\014crow" +
      "dcontrol\"$\n\013EmailAnswer\022\025\n\rauthorization" +
      "\030\001 \001(\tB0\n,edu.kit.ipd.crowdcontrol.worke" +
      "rservice.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crowdcontrol_EmailAnswer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crowdcontrol_EmailAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_EmailAnswer_descriptor,
        new java.lang.String[] { "Authorization", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
