// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: answer.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface AnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.Answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 reservation = 1;</code>
   */
  int getReservation();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional int32 experiment_id = 3;</code>
   */
  int getExperimentId();

  /**
   * <code>optional int32 worker = 4;</code>
   */
  int getWorker();

  /**
   * <code>optional string content = 5;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional int64 time = 6;</code>
   */
  long getTime();

  /**
   * <code>optional int32 quality = 7;</code>
   */
  int getQuality();

  /**
   * <code>repeated .crowdcontrol.Rating ratings = 8;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Rating> 
      getRatingsList();
  /**
   * <code>repeated .crowdcontrol.Rating ratings = 8;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Rating getRatings(int index);
  /**
   * <code>repeated .crowdcontrol.Rating ratings = 8;</code>
   */
  int getRatingsCount();
  /**
   * <code>repeated .crowdcontrol.Rating ratings = 8;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.RatingOrBuilder> 
      getRatingsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Rating ratings = 8;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.RatingOrBuilder getRatingsOrBuilder(
      int index);
}
