// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boolean.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface BooleanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.Boolean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool value = 1;</code>
   */
  boolean getValue();
}
