// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraint.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface ConstraintOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.Constraint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
