// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: experiment.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface ExperimentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.Experiment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional .crowdcontrol.Experiment.State state = 4;</code>
   */
  int getStateValue();
  /**
   * <code>optional .crowdcontrol.Experiment.State state = 4;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.State getState();

  /**
   * <code>optional .crowdcontrol.AnswerType answer_type = 5;</code>
   */
  int getAnswerTypeValue();
  /**
   * <code>optional .crowdcontrol.AnswerType answer_type = 5;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerType getAnswerType();

  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_task_chooser = 6;</code>
   */
  boolean hasAlgorithmTaskChooser();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_task_chooser = 6;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOption getAlgorithmTaskChooser();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_task_chooser = 6;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOptionOrBuilder getAlgorithmTaskChooserOrBuilder();

  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_answer = 7;</code>
   */
  boolean hasAlgorithmQualityAnswer();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_answer = 7;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOption getAlgorithmQualityAnswer();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_answer = 7;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOptionOrBuilder getAlgorithmQualityAnswerOrBuilder();

  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_rating = 8;</code>
   */
  boolean hasAlgorithmQualityRating();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_rating = 8;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOption getAlgorithmQualityRating();
  /**
   * <code>optional .crowdcontrol.AlgorithmOption algorithm_quality_rating = 8;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AlgorithmOptionOrBuilder getAlgorithmQualityRatingOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer answers_per_worker = 9;</code>
   */
  boolean hasAnswersPerWorker();
  /**
   * <code>optional .crowdcontrol.Integer answers_per_worker = 9;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getAnswersPerWorker();
  /**
   * <code>optional .crowdcontrol.Integer answers_per_worker = 9;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getAnswersPerWorkerOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer ratings_per_worker = 10;</code>
   */
  boolean hasRatingsPerWorker();
  /**
   * <code>optional .crowdcontrol.Integer ratings_per_worker = 10;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getRatingsPerWorker();
  /**
   * <code>optional .crowdcontrol.Integer ratings_per_worker = 10;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getRatingsPerWorkerOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer ratings_per_answer = 11;</code>
   */
  boolean hasRatingsPerAnswer();
  /**
   * <code>optional .crowdcontrol.Integer ratings_per_answer = 11;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getRatingsPerAnswer();
  /**
   * <code>optional .crowdcontrol.Integer ratings_per_answer = 11;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getRatingsPerAnswerOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer needed_answers = 12;</code>
   */
  boolean hasNeededAnswers();
  /**
   * <code>optional .crowdcontrol.Integer needed_answers = 12;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getNeededAnswers();
  /**
   * <code>optional .crowdcontrol.Integer needed_answers = 12;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getNeededAnswersOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer payment_base = 13;</code>
   */
  boolean hasPaymentBase();
  /**
   * <code>optional .crowdcontrol.Integer payment_base = 13;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getPaymentBase();
  /**
   * <code>optional .crowdcontrol.Integer payment_base = 13;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getPaymentBaseOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer payment_answer = 14;</code>
   */
  boolean hasPaymentAnswer();
  /**
   * <code>optional .crowdcontrol.Integer payment_answer = 14;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getPaymentAnswer();
  /**
   * <code>optional .crowdcontrol.Integer payment_answer = 14;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getPaymentAnswerOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer payment_rating = 15;</code>
   */
  boolean hasPaymentRating();
  /**
   * <code>optional .crowdcontrol.Integer payment_rating = 15;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getPaymentRating();
  /**
   * <code>optional .crowdcontrol.Integer payment_rating = 15;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getPaymentRatingOrBuilder();

  /**
   * <code>repeated .crowdcontrol.Constraint constraints = 16;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Constraint> 
      getConstraintsList();
  /**
   * <code>repeated .crowdcontrol.Constraint constraints = 16;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Constraint getConstraints(int index);
  /**
   * <code>repeated .crowdcontrol.Constraint constraints = 16;</code>
   */
  int getConstraintsCount();
  /**
   * <code>repeated .crowdcontrol.Constraint constraints = 16;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.ConstraintOrBuilder> 
      getConstraintsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Constraint constraints = 16;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.ConstraintOrBuilder getConstraintsOrBuilder(
      int index);

  /**
   * <code>repeated .crowdcontrol.Tag tags = 17;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Tag> 
      getTagsList();
  /**
   * <code>repeated .crowdcontrol.Tag tags = 17;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Tag getTags(int index);
  /**
   * <code>repeated .crowdcontrol.Tag tags = 17;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .crowdcontrol.Tag tags = 17;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.TagOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Tag tags = 17;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.TagOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>repeated .crowdcontrol.Experiment.Population populations = 18;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.Population> 
      getPopulationsList();
  /**
   * <code>repeated .crowdcontrol.Experiment.Population populations = 18;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.Population getPopulations(int index);
  /**
   * <code>repeated .crowdcontrol.Experiment.Population populations = 18;</code>
   */
  int getPopulationsCount();
  /**
   * <code>repeated .crowdcontrol.Experiment.Population populations = 18;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.PopulationOrBuilder> 
      getPopulationsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Experiment.Population populations = 18;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.PopulationOrBuilder getPopulationsOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; placeholders = 19;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPlaceholders();

  /**
   * <code>optional .crowdcontrol.Integer payment_quality_threshold = 20;</code>
   */
  boolean hasPaymentQualityThreshold();
  /**
   * <code>optional .crowdcontrol.Integer payment_quality_threshold = 20;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getPaymentQualityThreshold();
  /**
   * <code>optional .crowdcontrol.Integer payment_quality_threshold = 20;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getPaymentQualityThresholdOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer worker_quality_threshold = 21;</code>
   */
  boolean hasWorkerQualityThreshold();
  /**
   * <code>optional .crowdcontrol.Integer worker_quality_threshold = 21;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getWorkerQualityThreshold();
  /**
   * <code>optional .crowdcontrol.Integer worker_quality_threshold = 21;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getWorkerQualityThresholdOrBuilder();

  /**
   * <code>optional .crowdcontrol.Integer template_id = 22;</code>
   */
  boolean hasTemplateId();
  /**
   * <code>optional .crowdcontrol.Integer template_id = 22;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Integer getTemplateId();
  /**
   * <code>optional .crowdcontrol.Integer template_id = 22;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.IntegerOrBuilder getTemplateIdOrBuilder();

  /**
   * <code>repeated .crowdcontrol.Experiment.RatingOption rating_options = 23;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.RatingOption> 
      getRatingOptionsList();
  /**
   * <code>repeated .crowdcontrol.Experiment.RatingOption rating_options = 23;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.RatingOption getRatingOptions(int index);
  /**
   * <code>repeated .crowdcontrol.Experiment.RatingOption rating_options = 23;</code>
   */
  int getRatingOptionsCount();
  /**
   * <code>repeated .crowdcontrol.Experiment.RatingOption rating_options = 23;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.RatingOptionOrBuilder> 
      getRatingOptionsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Experiment.RatingOption rating_options = 23;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Experiment.RatingOptionOrBuilder getRatingOptionsOrBuilder(
      int index);
}
