// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

/**
 * Protobuf type {@code crowdcontrol.Notification}
 */
public  final class Notification extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:crowdcontrol.Notification)
    NotificationOrBuilder {
  // Use Notification.newBuilder() to construct.
  private Notification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Notification() {
    id_ = 0;
    name_ = "";
    description_ = "";
    query_ = "";
    checkPeriod_ = 0;
    emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Notification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            query_ = s;
            break;
          }
          case 40: {

            checkPeriod_ = input.readInt32();
            break;
          }
          case 50: {
            edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder subBuilder = null;
            if (sendOnce_ != null) {
              subBuilder = sendOnce_.toBuilder();
            }
            sendOnce_ = input.readMessage(edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sendOnce_);
              sendOnce_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              emails_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            emails_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        emails_ = emails_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOuterClass.internal_static_crowdcontrol_Notification_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOuterClass.internal_static_crowdcontrol_Notification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.class, edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>optional string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_FIELD_NUMBER = 4;
  private volatile java.lang.Object query_;
  /**
   * <code>optional string query = 4;</code>
   */
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <code>optional string query = 4;</code>
   */
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECK_PERIOD_FIELD_NUMBER = 5;
  private int checkPeriod_;
  /**
   * <code>optional int32 check_period = 5;</code>
   */
  public int getCheckPeriod() {
    return checkPeriod_;
  }

  public static final int SEND_ONCE_FIELD_NUMBER = 6;
  private edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean sendOnce_;
  /**
   * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
   */
  public boolean hasSendOnce() {
    return sendOnce_ != null;
  }
  /**
   * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
   */
  public edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean getSendOnce() {
    return sendOnce_ == null ? edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.getDefaultInstance() : sendOnce_;
  }
  /**
   * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
   */
  public edu.kit.ipd.crowdcontrol.objectservice.proto.BooleanOrBuilder getSendOnceOrBuilder() {
    return getSendOnce();
  }

  public static final int EMAILS_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList emails_;
  /**
   * <code>repeated string emails = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEmailsList() {
    return emails_;
  }
  /**
   * <code>repeated string emails = 7;</code>
   */
  public int getEmailsCount() {
    return emails_.size();
  }
  /**
   * <code>repeated string emails = 7;</code>
   */
  public java.lang.String getEmails(int index) {
    return emails_.get(index);
  }
  /**
   * <code>repeated string emails = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEmailsBytes(int index) {
    return emails_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
    }
    if (!getQueryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, query_);
    }
    if (checkPeriod_ != 0) {
      output.writeInt32(5, checkPeriod_);
    }
    if (sendOnce_ != null) {
      output.writeMessage(6, getSendOnce());
    }
    for (int i = 0; i < emails_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, emails_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
    }
    if (!getQueryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, query_);
    }
    if (checkPeriod_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, checkPeriod_);
    }
    if (sendOnce_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getSendOnce());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < emails_.size(); i++) {
        dataSize += computeStringSizeNoTag(emails_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEmailsList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.kit.ipd.crowdcontrol.objectservice.proto.Notification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crowdcontrol.Notification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crowdcontrol.Notification)
      edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOuterClass.internal_static_crowdcontrol_Notification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOuterClass.internal_static_crowdcontrol_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.class, edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.Builder.class);
    }

    // Construct using edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      description_ = "";

      query_ = "";

      checkPeriod_ = 0;

      if (sendOnceBuilder_ == null) {
        sendOnce_ = null;
      } else {
        sendOnce_ = null;
        sendOnceBuilder_ = null;
      }
      emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.kit.ipd.crowdcontrol.objectservice.proto.NotificationOuterClass.internal_static_crowdcontrol_Notification_descriptor;
    }

    public edu.kit.ipd.crowdcontrol.objectservice.proto.Notification getDefaultInstanceForType() {
      return edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.getDefaultInstance();
    }

    public edu.kit.ipd.crowdcontrol.objectservice.proto.Notification build() {
      edu.kit.ipd.crowdcontrol.objectservice.proto.Notification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public edu.kit.ipd.crowdcontrol.objectservice.proto.Notification buildPartial() {
      edu.kit.ipd.crowdcontrol.objectservice.proto.Notification result = new edu.kit.ipd.crowdcontrol.objectservice.proto.Notification(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.query_ = query_;
      result.checkPeriod_ = checkPeriod_;
      if (sendOnceBuilder_ == null) {
        result.sendOnce_ = sendOnce_;
      } else {
        result.sendOnce_ = sendOnceBuilder_.build();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        emails_ = emails_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.emails_ = emails_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.kit.ipd.crowdcontrol.objectservice.proto.Notification) {
        return mergeFrom((edu.kit.ipd.crowdcontrol.objectservice.proto.Notification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.kit.ipd.crowdcontrol.objectservice.proto.Notification other) {
      if (other == edu.kit.ipd.crowdcontrol.objectservice.proto.Notification.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        onChanged();
      }
      if (other.getCheckPeriod() != 0) {
        setCheckPeriod(other.getCheckPeriod());
      }
      if (other.hasSendOnce()) {
        mergeSendOnce(other.getSendOnce());
      }
      if (!other.emails_.isEmpty()) {
        if (emails_.isEmpty()) {
          emails_ = other.emails_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureEmailsIsMutable();
          emails_.addAll(other.emails_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.kit.ipd.crowdcontrol.objectservice.proto.Notification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.kit.ipd.crowdcontrol.objectservice.proto.Notification) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object query_ = "";
    /**
     * <code>optional string query = 4;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string query = 4;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string query = 4;</code>
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string query = 4;</code>
     */
    public Builder clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
      onChanged();
      return this;
    }
    /**
     * <code>optional string query = 4;</code>
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      query_ = value;
      onChanged();
      return this;
    }

    private int checkPeriod_ ;
    /**
     * <code>optional int32 check_period = 5;</code>
     */
    public int getCheckPeriod() {
      return checkPeriod_;
    }
    /**
     * <code>optional int32 check_period = 5;</code>
     */
    public Builder setCheckPeriod(int value) {
      
      checkPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 check_period = 5;</code>
     */
    public Builder clearCheckPeriod() {
      
      checkPeriod_ = 0;
      onChanged();
      return this;
    }

    private edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean sendOnce_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean, edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder, edu.kit.ipd.crowdcontrol.objectservice.proto.BooleanOrBuilder> sendOnceBuilder_;
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public boolean hasSendOnce() {
      return sendOnceBuilder_ != null || sendOnce_ != null;
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean getSendOnce() {
      if (sendOnceBuilder_ == null) {
        return sendOnce_ == null ? edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.getDefaultInstance() : sendOnce_;
      } else {
        return sendOnceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public Builder setSendOnce(edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean value) {
      if (sendOnceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sendOnce_ = value;
        onChanged();
      } else {
        sendOnceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public Builder setSendOnce(
        edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder builderForValue) {
      if (sendOnceBuilder_ == null) {
        sendOnce_ = builderForValue.build();
        onChanged();
      } else {
        sendOnceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public Builder mergeSendOnce(edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean value) {
      if (sendOnceBuilder_ == null) {
        if (sendOnce_ != null) {
          sendOnce_ =
            edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.newBuilder(sendOnce_).mergeFrom(value).buildPartial();
        } else {
          sendOnce_ = value;
        }
        onChanged();
      } else {
        sendOnceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public Builder clearSendOnce() {
      if (sendOnceBuilder_ == null) {
        sendOnce_ = null;
        onChanged();
      } else {
        sendOnce_ = null;
        sendOnceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder getSendOnceBuilder() {
      
      onChanged();
      return getSendOnceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    public edu.kit.ipd.crowdcontrol.objectservice.proto.BooleanOrBuilder getSendOnceOrBuilder() {
      if (sendOnceBuilder_ != null) {
        return sendOnceBuilder_.getMessageOrBuilder();
      } else {
        return sendOnce_ == null ?
            edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.getDefaultInstance() : sendOnce_;
      }
    }
    /**
     * <code>optional .crowdcontrol.Boolean send_once = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean, edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder, edu.kit.ipd.crowdcontrol.objectservice.proto.BooleanOrBuilder> 
        getSendOnceFieldBuilder() {
      if (sendOnceBuilder_ == null) {
        sendOnceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean, edu.kit.ipd.crowdcontrol.objectservice.proto.Boolean.Builder, edu.kit.ipd.crowdcontrol.objectservice.proto.BooleanOrBuilder>(
                getSendOnce(),
                getParentForChildren(),
                isClean());
        sendOnce_ = null;
      }
      return sendOnceBuilder_;
    }

    private com.google.protobuf.LazyStringList emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEmailsIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        emails_ = new com.google.protobuf.LazyStringArrayList(emails_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEmailsList() {
      return emails_.getUnmodifiableView();
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public int getEmailsCount() {
      return emails_.size();
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public java.lang.String getEmails(int index) {
      return emails_.get(index);
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEmailsBytes(int index) {
      return emails_.getByteString(index);
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public Builder setEmails(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
      emails_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public Builder addEmails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
      emails_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public Builder addAllEmails(
        java.lang.Iterable<java.lang.String> values) {
      ensureEmailsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, emails_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public Builder clearEmails() {
      emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string emails = 7;</code>
     */
    public Builder addEmailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEmailsIsMutable();
      emails_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:crowdcontrol.Notification)
  }

  // @@protoc_insertion_point(class_scope:crowdcontrol.Notification)
  private static final edu.kit.ipd.crowdcontrol.objectservice.proto.Notification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.kit.ipd.crowdcontrol.objectservice.proto.Notification();
  }

  public static edu.kit.ipd.crowdcontrol.objectservice.proto.Notification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notification>
      PARSER = new com.google.protobuf.AbstractParser<Notification>() {
    public Notification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Notification(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Notification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Notification> getParserForType() {
    return PARSER;
  }

  public edu.kit.ipd.crowdcontrol.objectservice.proto.Notification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

