// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface TemplateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.Template)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional .crowdcontrol.AnswerType answer_type = 4;</code>
   */
  int getAnswerTypeValue();
  /**
   * <code>optional .crowdcontrol.AnswerType answer_type = 4;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerType getAnswerType();

  /**
   * <code>repeated .crowdcontrol.Template.RatingOption rating_options = 5;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Template.RatingOption> 
      getRatingOptionsList();
  /**
   * <code>repeated .crowdcontrol.Template.RatingOption rating_options = 5;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Template.RatingOption getRatingOptions(int index);
  /**
   * <code>repeated .crowdcontrol.Template.RatingOption rating_options = 5;</code>
   */
  int getRatingOptionsCount();
  /**
   * <code>repeated .crowdcontrol.Template.RatingOption rating_options = 5;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.Template.RatingOptionOrBuilder> 
      getRatingOptionsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Template.RatingOption rating_options = 5;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Template.RatingOptionOrBuilder getRatingOptionsOrBuilder(
      int index);
}
