// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public final class TemplateOuterClass {
  private TemplateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_crowdcontrol_Template_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crowdcontrol_Template_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016template.proto\022\014crowdcontrol\032\021answer_t" +
      "ype.proto\"d\n\010Template\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022-\n\013answer_type\030" +
      "\004 \001(\0162\030.crowdcontrol.AnswerTypeB0\n,edu.k" +
      "it.ipd.crowdcontrol.objectservice.protoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_crowdcontrol_Template_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crowdcontrol_Template_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crowdcontrol_Template_descriptor,
        new java.lang.String[] { "Id", "Name", "Content", "AnswerType", });
    edu.kit.ipd.crowdcontrol.objectservice.proto.AnswerTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
