// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_list.proto

package edu.kit.ipd.crowdcontrol.objectservice.proto;

public interface WorkerListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crowdcontrol.WorkerList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .crowdcontrol.Worker items = 1;</code>
   */
  java.util.List<edu.kit.ipd.crowdcontrol.objectservice.proto.Worker> 
      getItemsList();
  /**
   * <code>repeated .crowdcontrol.Worker items = 1;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.Worker getItems(int index);
  /**
   * <code>repeated .crowdcontrol.Worker items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .crowdcontrol.Worker items = 1;</code>
   */
  java.util.List<? extends edu.kit.ipd.crowdcontrol.objectservice.proto.WorkerOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .crowdcontrol.Worker items = 1;</code>
   */
  edu.kit.ipd.crowdcontrol.objectservice.proto.WorkerOrBuilder getItemsOrBuilder(
      int index);
}
