/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Giftcodes implements java.io.Serializable {

	private static final long serialVersionUID = -1284164803;

	private java.lang.Integer idgiftcodes;
	private java.lang.String  code;
	private java.lang.Integer amount;

	public Giftcodes() {}

	public Giftcodes(
		java.lang.Integer idgiftcodes,
		java.lang.String  code,
		java.lang.Integer amount
	) {
		this.idgiftcodes = idgiftcodes;
		this.code = code;
		this.amount = amount;
	}

	public java.lang.Integer getIdgiftcodes() {
		return this.idgiftcodes;
	}

	public void setIdgiftcodes(java.lang.Integer idgiftcodes) {
		this.idgiftcodes = idgiftcodes;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}
}
