/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.workerservice.database.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrol
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrol.Answer
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answer ANSWER = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answer.ANSWER;

	/**
	 * The table crowdcontrol.Constraint
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Constraint CONSTRAINT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Constraint.CONSTRAINT;

	/**
	 * The table crowdcontrol.Experiment
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experiment EXPERIMENT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrol.ExperimentsPopulation
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experimentspopulation EXPERIMENTSPOPULATION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION;

	/**
	 * The table crowdcontrol.GiftCode
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Giftcode GIFTCODE = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE;

	/**
	 * The table crowdcontrol.Notification
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Notification NOTIFICATION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Notification.NOTIFICATION;

	/**
	 * The table crowdcontrol.Payment
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Payment PAYMENT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT;

	/**
	 * The table crowdcontrol.Platform
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Platform PLATFORM = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Platform.PLATFORM;

	/**
	 * The table crowdcontrol.Population
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Population POPULATION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Population.POPULATION;

	/**
	 * The table crowdcontrol.PopulationAnswerOption
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationansweroption POPULATIONANSWEROPTION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationansweroption.POPULATIONANSWEROPTION;

	/**
	 * The table crowdcontrol.PopulationResult
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationresult POPULATIONRESULT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationresult.POPULATIONRESULT;

	/**
	 * The table crowdcontrol.Rating
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Rating RATING = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Rating.RATING;

	/**
	 * The table crowdcontrol.Tag
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Tag TAG = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Tag.TAG;

	/**
	 * The table crowdcontrol.Task
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task TASK = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK;

	/**
	 * The table crowdcontrol.Template
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Template TEMPLATE = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Template.TEMPLATE;

	/**
	 * The table crowdcontrol.Worker
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Worker WORKER = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Worker.WORKER;
}
