/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.workerservice.database.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crowdcontrol
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crowdcontrol.Answers
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers ANSWERS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS;

	/**
	 * The table crowdcontrol.Constraints
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Constraints CONSTRAINTS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Constraints.CONSTRAINTS;

	/**
	 * The table crowdcontrol.Experiment
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experiment EXPERIMENT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experiment.EXPERIMENT;

	/**
	 * The table crowdcontrol.ExperimentsPopulation
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experimentspopulation EXPERIMENTSPOPULATION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION;

	/**
	 * The table crowdcontrol.Payment
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Payment PAYMENT = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT;

	/**
	 * The table crowdcontrol.Platforms
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Platforms PLATFORMS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Platforms.PLATFORMS;

	/**
	 * The table crowdcontrol.Population
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Population POPULATION = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Population.POPULATION;

	/**
	 * The table crowdcontrol.PopulationAnswersOptions
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationanswersoptions POPULATIONANSWERSOPTIONS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationanswersoptions.POPULATIONANSWERSOPTIONS;

	/**
	 * The table crowdcontrol.PopulationResults
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationresults POPULATIONRESULTS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Populationresults.POPULATIONRESULTS;

	/**
	 * The table crowdcontrol.Ratings
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Ratings RATINGS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Ratings.RATINGS;

	/**
	 * The table crowdcontrol.Tags
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Tags TAGS = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Tags.TAGS;

	/**
	 * The table crowdcontrol.Task
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task TASK = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK;

	/**
	 * The table crowdcontrol.Templates
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Templates TEMPLATES = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Templates.TEMPLATES;

	/**
	 * The table crowdcontrol.TemplateVariables
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Templatevariables TEMPLATEVARIABLES = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Templatevariables.TEMPLATEVARIABLES;

	/**
	 * The table crowdcontrol.Worker
	 */
	public static final edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Worker WORKER = edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Worker.WORKER;
}
