/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlgorithmRatingQualityParamDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam, java.lang.Integer> {

	/**
	 * Create a new AlgorithmRatingQualityParamDao without any configuration
	 */
	public AlgorithmRatingQualityParamDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam.class);
	}

	/**
	 * Create a new AlgorithmRatingQualityParamDao with an attached configuration
	 */
	public AlgorithmRatingQualityParamDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam object) {
		return object.getIdAlgorithmRatingQualityParam();
	}

	/**
	 * Fetch records that have <code>id_Algorithm_Rating_Quality_Param IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam> fetchByIdAlgorithmRatingQualityParam(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.ID_ALGORITHM_RATING_QUALITY_PARAM, values);
	}

	/**
	 * Fetch a unique record that has <code>id_Algorithm_Rating_Quality_Param = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam fetchOneByIdAlgorithmRatingQualityParam(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.ID_ALGORITHM_RATING_QUALITY_PARAM, value);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam> fetchByDescription(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>regex IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam> fetchByRegex(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.REGEX, values);
	}

	/**
	 * Fetch records that have <code>algorithm IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam> fetchByAlgorithm(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.ALGORITHM, values);
	}

	/**
	 * Fetch records that have <code>data IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.AlgorithmRatingQualityParam> fetchByData(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM.DATA, values);
	}
}
