/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalibrationDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.CalibrationRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration, java.lang.Integer> {

	/**
	 * Create a new CalibrationDao without any configuration
	 */
	public CalibrationDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration.class);
	}

	/**
	 * Create a new CalibrationDao with an attached configuration
	 */
	public CalibrationDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration object) {
		return object.getIdCalibration();
	}

	/**
	 * Fetch records that have <code>id_calibration IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration> fetchByIdCalibration(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.ID_CALIBRATION, values);
	}

	/**
	 * Fetch a unique record that has <code>id_calibration = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration fetchOneByIdCalibration(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.ID_CALIBRATION, value);
	}

	/**
	 * Fetch records that have <code>property IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration> fetchByProperty(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.PROPERTY, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration> fetchByName(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.NAME, values);
	}

	/**
	 * Fetch records that have <code>experiment IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration> fetchByExperiment(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.EXPERIMENT, values);
	}

	/**
	 * Fetch a unique record that has <code>experiment = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Calibration fetchOneByExperiment(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Calibration.CALIBRATION.EXPERIMENT, value);
	}
}
