/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentspopulationDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentspopulationRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation, java.lang.String> {

	/**
	 * Create a new ExperimentspopulationDao without any configuration
	 */
	public ExperimentspopulationDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation.class);
	}

	/**
	 * Create a new ExperimentspopulationDao with an attached configuration
	 */
	public ExperimentspopulationDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation object) {
		return object.getIdExperimentsPopulation();
	}

	/**
	 * Fetch records that have <code>id_experiments_population IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation> fetchByIdExperimentsPopulation(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.ID_EXPERIMENTS_POPULATION, values);
	}

	/**
	 * Fetch a unique record that has <code>id_experiments_population = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation fetchOneByIdExperimentsPopulation(java.lang.String value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.ID_EXPERIMENTS_POPULATION, value);
	}

	/**
	 * Fetch records that have <code>population_user IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation> fetchByPopulationUser(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.POPULATION_USER, values);
	}

	/**
	 * Fetch records that have <code>answer IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation> fetchByAnswer(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.ANSWER, values);
	}

	/**
	 * Fetch records that have <code>referenced_platform IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation> fetchByReferencedPlatform(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.REFERENCED_PLATFORM, values);
	}

	/**
	 * Fetch records that have <code>not IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Experimentspopulation> fetchByNot(java.lang.Boolean... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Experimentspopulation.EXPERIMENTSPOPULATION.NOT, values);
	}
}
