/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentsPlatformsDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms, java.lang.Integer> {

	/**
	 * Create a new ExperimentsPlatformsDao without any configuration
	 */
	public ExperimentsPlatformsDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms.class);
	}

	/**
	 * Create a new ExperimentsPlatformsDao with an attached configuration
	 */
	public ExperimentsPlatformsDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms object) {
		return object.getIdexperimentsPlatforms();
	}

	/**
	 * Fetch records that have <code>idExperiments_Platforms IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms> fetchByIdexperimentsPlatforms(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS.IDEXPERIMENTS_PLATFORMS, values);
	}

	/**
	 * Fetch a unique record that has <code>idExperiments_Platforms = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms fetchOneByIdexperimentsPlatforms(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS.IDEXPERIMENTS_PLATFORMS, value);
	}

	/**
	 * Fetch records that have <code>experiment IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms> fetchByExperiment(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS.EXPERIMENT, values);
	}

	/**
	 * Fetch records that have <code>platform IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.ExperimentsPlatforms> fetchByPlatform(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS.PLATFORM, values);
	}
}
