/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GiftcodeDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.GiftcodeRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode, java.lang.Integer> {

	/**
	 * Create a new GiftcodeDao without any configuration
	 */
	public GiftcodeDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode.class);
	}

	/**
	 * Create a new GiftcodeDao with an attached configuration
	 */
	public GiftcodeDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode object) {
		return object.getIdgiftcode();
	}

	/**
	 * Fetch records that have <code>idGiftCode IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode> fetchByIdgiftcode(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE.IDGIFTCODE, values);
	}

	/**
	 * Fetch a unique record that has <code>idGiftCode = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode fetchOneByIdgiftcode(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE.IDGIFTCODE, value);
	}

	/**
	 * Fetch records that have <code>code IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode> fetchByCode(java.lang.String... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE.CODE, values);
	}

	/**
	 * Fetch records that have <code>amount IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Giftcode> fetchByAmount(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Giftcode.GIFTCODE.AMOUNT, values);
	}
}
