/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.PaymentRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment, java.lang.Integer> {

	/**
	 * Create a new PaymentDao without any configuration
	 */
	public PaymentDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment.class);
	}

	/**
	 * Create a new PaymentDao with an attached configuration
	 */
	public PaymentDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment object) {
		return object.getIdPayment();
	}

	/**
	 * Fetch records that have <code>id_payment IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByIdPayment(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.ID_PAYMENT, values);
	}

	/**
	 * Fetch a unique record that has <code>id_payment = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment fetchOneByIdPayment(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.ID_PAYMENT, value);
	}

	/**
	 * Fetch records that have <code>worker_id IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByWorkerId(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.WORKER_ID, values);
	}

	/**
	 * Fetch records that have <code>experiment_id IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByExperimentId(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.EXPERIMENT_ID, values);
	}

	/**
	 * Fetch records that have <code>timestamp IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByTimestamp(java.sql.Timestamp... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.TIMESTAMP, values);
	}

	/**
	 * Fetch records that have <code>amount IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByAmount(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.AMOUNT, values);
	}

	/**
	 * Fetch records that have <code>giftcode IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Payment> fetchByGiftcode(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Payment.PAYMENT.GIFTCODE, values);
	}
}
