/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PopulationResultDao extends org.jooq.impl.DAOImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.PopulationResultRecord, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult, java.lang.Integer> {

	/**
	 * Create a new PopulationResultDao without any configuration
	 */
	public PopulationResultDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult.class);
	}

	/**
	 * Create a new PopulationResultDao with an attached configuration
	 */
	public PopulationResultDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult object) {
		return object.getIdPopulationResult();
	}

	/**
	 * Fetch records that have <code>id_population_result IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult> fetchByIdPopulationResult(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT.ID_POPULATION_RESULT, values);
	}

	/**
	 * Fetch a unique record that has <code>id_population_result = value</code>
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult fetchOneByIdPopulationResult(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT.ID_POPULATION_RESULT, value);
	}

	/**
	 * Fetch records that have <code>worker IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult> fetchByWorker(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT.WORKER, values);
	}

	/**
	 * Fetch records that have <code>answer IN (values)</code>
	 */
	public java.util.List<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.PopulationResult> fetchByAnswer(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.PopulationResult.POPULATION_RESULT.ANSWER, values);
	}
}
