/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.daos;

import edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos.Rating;
import edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.RatingRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingDao extends org.jooq.impl.DAOImpl<RatingRecord, Rating, java.lang.Integer> {

	/**
	 * Create a new RatingDao without any configuration
	 */
	public RatingDao() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING, Rating.class);
	}

	/**
	 * Create a new RatingDao with an attached configuration
	 */
	public RatingDao(org.jooq.Configuration configuration) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING, Rating.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(Rating object) {
		return object.getIdrating();
	}

	/**
	 * Fetch records that have <code>idRating IN (values)</code>
	 */
	public java.util.List<Rating> fetchByIdrating(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.IDRATING, values);
	}

	/**
	 * Fetch a unique record that has <code>idRating = value</code>
	 */
	public Rating fetchOneByIdrating(java.lang.Integer value) {
		return fetchOne(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.IDRATING, value);
	}

	/**
	 * Fetch records that have <code>task IN (values)</code>
	 */
	public java.util.List<Rating> fetchByTask(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.TASK, values);
	}

	/**
	 * Fetch records that have <code>answer_r IN (values)</code>
	 */
	public java.util.List<Rating> fetchByAnswerR(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.ANSWER_R, values);
	}

	/**
	 * Fetch records that have <code>timestamp IN (values)</code>
	 */
	public java.util.List<Rating> fetchByTimestamp(java.sql.Timestamp... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.TIMESTAMP, values);
	}

	/**
	 * Fetch records that have <code>rating IN (values)</code>
	 */
	public java.util.List<Rating> fetchByRating(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.RATING_, values);
	}

	/**
	 * Fetch records that have <code>worker_id IN (values)</code>
	 */
	public java.util.List<Rating> fetchByWorkerId(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.WORKER_ID, values);
	}

	/**
	 * Fetch records that have <code>quality IN (values)</code>
	 */
	public java.util.List<Rating> fetchByQuality(java.lang.Integer... values) {
		return fetch(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.Rating.RATING.QUALITY, values);
	}
}
