/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Answer implements java.io.Serializable {

	private static final long serialVersionUID = 2027099591;

	private java.lang.Integer  idAnswer;
	private java.lang.Integer  task;
	private java.lang.String   answer;
	private java.sql.Timestamp timestamp;
	private java.lang.Integer  workerId;
	private java.lang.Integer  quality;

	public Answer() {}

	public Answer(
		java.lang.Integer  idAnswer,
		java.lang.Integer  task,
		java.lang.String   answer,
		java.sql.Timestamp timestamp,
		java.lang.Integer  workerId,
		java.lang.Integer  quality
	) {
		this.idAnswer = idAnswer;
		this.task = task;
		this.answer = answer;
		this.timestamp = timestamp;
		this.workerId = workerId;
		this.quality = quality;
	}

	public java.lang.Integer getIdAnswer() {
		return this.idAnswer;
	}

	public void setIdAnswer(java.lang.Integer idAnswer) {
		this.idAnswer = idAnswer;
	}

	public java.lang.Integer getTask() {
		return this.task;
	}

	public void setTask(java.lang.Integer task) {
		this.task = task;
	}

	public java.lang.String getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.String answer) {
		this.answer = answer;
	}

	public java.sql.Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.sql.Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.Integer getWorkerId() {
		return this.workerId;
	}

	public void setWorkerId(java.lang.Integer workerId) {
		this.workerId = workerId;
	}

	public java.lang.Integer getQuality() {
		return this.quality;
	}

	public void setQuality(java.lang.Integer quality) {
		this.quality = quality;
	}
}
