/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalibrationAnswerOption implements java.io.Serializable {

	private static final long serialVersionUID = 168356248;

	private java.lang.Integer idCalibrationAnswerOption;
	private java.lang.Integer calibration;
	private java.lang.String  answer;

	public CalibrationAnswerOption() {}

	public CalibrationAnswerOption(
		java.lang.Integer idCalibrationAnswerOption,
		java.lang.Integer calibration,
		java.lang.String  answer
	) {
		this.idCalibrationAnswerOption = idCalibrationAnswerOption;
		this.calibration = calibration;
		this.answer = answer;
	}

	public java.lang.Integer getIdCalibrationAnswerOption() {
		return this.idCalibrationAnswerOption;
	}

	public void setIdCalibrationAnswerOption(java.lang.Integer idCalibrationAnswerOption) {
		this.idCalibrationAnswerOption = idCalibrationAnswerOption;
	}

	public java.lang.Integer getCalibration() {
		return this.calibration;
	}

	public void setCalibration(java.lang.Integer calibration) {
		this.calibration = calibration;
	}

	public java.lang.String getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.String answer) {
		this.answer = answer;
	}
}
