/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experimentspopulation implements java.io.Serializable {

	private static final long serialVersionUID = -1133568364;

	private java.lang.String  idExperimentsPopulation;
	private java.lang.Integer populationUser;
	private java.lang.Integer answer;
	private java.lang.String  referencedPlatform;
	private java.lang.Boolean not;

	public Experimentspopulation() {}

	public Experimentspopulation(
		java.lang.String  idExperimentsPopulation,
		java.lang.Integer populationUser,
		java.lang.Integer answer,
		java.lang.String  referencedPlatform,
		java.lang.Boolean not
	) {
		this.idExperimentsPopulation = idExperimentsPopulation;
		this.populationUser = populationUser;
		this.answer = answer;
		this.referencedPlatform = referencedPlatform;
		this.not = not;
	}

	public java.lang.String getIdExperimentsPopulation() {
		return this.idExperimentsPopulation;
	}

	public void setIdExperimentsPopulation(java.lang.String idExperimentsPopulation) {
		this.idExperimentsPopulation = idExperimentsPopulation;
	}

	public java.lang.Integer getPopulationUser() {
		return this.populationUser;
	}

	public void setPopulationUser(java.lang.Integer populationUser) {
		this.populationUser = populationUser;
	}

	public java.lang.Integer getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.Integer answer) {
		this.answer = answer;
	}

	public java.lang.String getReferencedPlatform() {
		return this.referencedPlatform;
	}

	public void setReferencedPlatform(java.lang.String referencedPlatform) {
		this.referencedPlatform = referencedPlatform;
	}

	public java.lang.Boolean getNot() {
		return this.not;
	}

	public void setNot(java.lang.Boolean not) {
		this.not = not;
	}
}
