/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification implements java.io.Serializable {

	private static final long serialVersionUID = -1565195390;

	private java.lang.Integer idNotification;
	private java.lang.String  name;
	private java.lang.String  description;
	private java.lang.Integer checkperiod;
	private java.lang.String  query;
	private java.lang.Boolean sendOnce;

	public Notification() {}

	public Notification(
		java.lang.Integer idNotification,
		java.lang.String  name,
		java.lang.String  description,
		java.lang.Integer checkperiod,
		java.lang.String  query,
		java.lang.Boolean sendOnce
	) {
		this.idNotification = idNotification;
		this.name = name;
		this.description = description;
		this.checkperiod = checkperiod;
		this.query = query;
		this.sendOnce = sendOnce;
	}

	public java.lang.Integer getIdNotification() {
		return this.idNotification;
	}

	public void setIdNotification(java.lang.Integer idNotification) {
		this.idNotification = idNotification;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getCheckperiod() {
		return this.checkperiod;
	}

	public void setCheckperiod(java.lang.Integer checkperiod) {
		this.checkperiod = checkperiod;
	}

	public java.lang.String getQuery() {
		return this.query;
	}

	public void setQuery(java.lang.String query) {
		this.query = query;
	}

	public java.lang.Boolean getSendOnce() {
		return this.sendOnce;
	}

	public void setSendOnce(java.lang.Boolean sendOnce) {
		this.sendOnce = sendOnce;
	}
}
