/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDao extends org.jooq.impl.DAOImpl<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.records.TaskRecord, edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task, java.lang.Integer> {

	/**
	 * Create a new TaskDao without any configuration
	 */
	public TaskDao() {
		super(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK, edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task.class);
	}

	/**
	 * Create a new TaskDao with an attached configuration
	 */
	public TaskDao(org.jooq.Configuration configuration) {
		super(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK, edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task object) {
		return object.getIdtask();
	}

	/**
	 * Fetch records that have <code>idTask IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task> fetchByIdtask(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.IDTASK, values);
	}

	/**
	 * Fetch a unique record that has <code>idTask = value</code>
	 */
	public edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task fetchOneByIdtask(java.lang.Integer value) {
		return fetchOne(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.IDTASK, value);
	}

	/**
	 * Fetch records that have <code>experiment IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task> fetchByExperiment(java.lang.Integer... values) {
		return fetch(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.EXPERIMENT, values);
	}

	/**
	 * Fetch records that have <code>running IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task> fetchByRunning(java.lang.Boolean... values) {
		return fetch(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.RUNNING, values);
	}

	/**
	 * Fetch records that have <code>platform_data IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task> fetchByPlatformData(java.lang.Object... values) {
		return fetch(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.PLATFORM_DATA, values);
	}

	/**
	 * Fetch records that have <code>crowd_platform IN (values)</code>
	 */
	public java.util.List<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.pojos.Task> fetchByCrowdPlatform(java.lang.String... values) {
		return fetch(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Task.TASK.CROWD_PLATFORM, values);
	}
}
