/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlgorithmRatingQualityParam extends org.jooq.impl.TableImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord> {

	private static final long serialVersionUID = 1940590582;

	/**
	 * The singleton instance of <code>crowdcontrol.Algorithm_Rating_Quality_Param</code>
	 */
	public static final edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam ALGORITHM_RATING_QUALITY_PARAM = new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord> getRecordType() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.id_Algorithm_Rating_Quality_Param</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.Integer> ID_ALGORITHM_RATING_QUALITY_PARAM = createField("id_Algorithm_Rating_Quality_Param", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.description</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.regex</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.String> REGEX = createField("regex", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.algorithm</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.String> ALGORITHM = createField("algorithm", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.data</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR.length(191), this, "");

	/**
	 * Create a <code>crowdcontrol.Algorithm_Rating_Quality_Param</code> table reference
	 */
	public AlgorithmRatingQualityParam() {
		this("Algorithm_Rating_Quality_Param", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Algorithm_Rating_Quality_Param</code> table reference
	 */
	public AlgorithmRatingQualityParam(java.lang.String alias) {
		this(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam.ALGORITHM_RATING_QUALITY_PARAM);
	}

	private AlgorithmRatingQualityParam(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlgorithmRatingQualityParam(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, java.lang.Integer> getIdentity() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.IDENTITY_ALGORITHM_RATING_QUALITY_PARAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord> getPrimaryKey() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_ALGORITHM_RATING_QUALITY_PARAM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_ALGORITHM_RATING_QUALITY_PARAM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityParamRecord, ?>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.REGERENCEDRATINQUALITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam as(java.lang.String alias) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam rename(java.lang.String name) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQualityParam(name, null);
	}
}
