/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables;


import edu.kit.ipd.crowdcontrol.objectservice.database.model.Crowdcontrol;
import edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys;
import edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.AlgorithmRatingQualityParamRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlgorithmRatingQualityParam extends TableImpl<AlgorithmRatingQualityParamRecord> {

	private static final long serialVersionUID = -694913141;

	/**
	 * The reference instance of <code>crowdcontrol.Algorithm_Rating_Quality_Param</code>
	 */
	public static final AlgorithmRatingQualityParam ALGORITHM_RATING_QUALITY_PARAM = new AlgorithmRatingQualityParam();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlgorithmRatingQualityParamRecord> getRecordType() {
		return AlgorithmRatingQualityParamRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.id_Algorithm_Rating_Quality_Param</code>.
	 */
	public final TableField<AlgorithmRatingQualityParamRecord, Integer> ID_ALGORITHM_RATING_QUALITY_PARAM = createField("id_Algorithm_Rating_Quality_Param", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.description</code>.
	 */
	public final TableField<AlgorithmRatingQualityParamRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.regex</code>.
	 */
	public final TableField<AlgorithmRatingQualityParamRecord, String> REGEX = createField("regex", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.algorithm</code>.
	 */
	public final TableField<AlgorithmRatingQualityParamRecord, String> ALGORITHM = createField("algorithm", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality_Param.data</code>.
	 */
	public final TableField<AlgorithmRatingQualityParamRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR.length(191), this, "");

	/**
	 * Create a <code>crowdcontrol.Algorithm_Rating_Quality_Param</code> table reference
	 */
	public AlgorithmRatingQualityParam() {
		this("Algorithm_Rating_Quality_Param", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Algorithm_Rating_Quality_Param</code> table reference
	 */
	public AlgorithmRatingQualityParam(String alias) {
		this(alias, ALGORITHM_RATING_QUALITY_PARAM);
	}

	private AlgorithmRatingQualityParam(String alias, Table<AlgorithmRatingQualityParamRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlgorithmRatingQualityParam(String alias, Table<AlgorithmRatingQualityParamRecord> aliased, Field<?>[] parameters) {
		super(alias, Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AlgorithmRatingQualityParamRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ALGORITHM_RATING_QUALITY_PARAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlgorithmRatingQualityParamRecord> getPrimaryKey() {
		return Keys.KEY_ALGORITHM_RATING_QUALITY_PARAM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlgorithmRatingQualityParamRecord>> getKeys() {
		return Arrays.<UniqueKey<AlgorithmRatingQualityParamRecord>>asList(Keys.KEY_ALGORITHM_RATING_QUALITY_PARAM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AlgorithmRatingQualityParamRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AlgorithmRatingQualityParamRecord, ?>>asList(Keys.REGERENCEDRATINQUALITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlgorithmRatingQualityParam as(String alias) {
		return new AlgorithmRatingQualityParam(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlgorithmRatingQualityParam rename(String name) {
		return new AlgorithmRatingQualityParam(name, null);
	}
}
