/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlgorithmRatingQuality extends org.jooq.impl.TableImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord> {

	private static final long serialVersionUID = 397196194;

	/**
	 * The singleton instance of <code>crowdcontrol.Algorithm_Rating_Quality</code>
	 */
	public static final edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality ALGORITHM_RATING_QUALITY = new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord> getRecordType() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality.id_Algorithm_Rating_Quality</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord, java.lang.String> ID_ALGORITHM_RATING_QUALITY = createField("id_Algorithm_Rating_Quality", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Algorithm_Rating_Quality.description</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrol.Algorithm_Rating_Quality</code> table reference
	 */
	public AlgorithmRatingQuality() {
		this("Algorithm_Rating_Quality", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Algorithm_Rating_Quality</code> table reference
	 */
	public AlgorithmRatingQuality(java.lang.String alias) {
		this(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality.ALGORITHM_RATING_QUALITY);
	}

	private AlgorithmRatingQuality(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlgorithmRatingQuality(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord> getPrimaryKey() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_ALGORITHM_RATING_QUALITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.AlgorithmRatingQualityRecord>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_ALGORITHM_RATING_QUALITY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality as(java.lang.String alias) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality rename(java.lang.String name) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmRatingQuality(name, null);
	}
}
