/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentsPlatforms extends org.jooq.impl.TableImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord> {

	private static final long serialVersionUID = 2107275496;

	/**
	 * The singleton instance of <code>crowdcontrol.Experiments_Platforms</code>
	 */
	public static final edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms EXPERIMENTS_PLATFORMS = new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord> getRecordType() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Experiments_Platforms.idExperiments_Platforms</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, java.lang.Integer> IDEXPERIMENTS_PLATFORMS = createField("idExperiments_Platforms", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Experiments_Platforms.experiment</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, java.lang.Integer> EXPERIMENT = createField("experiment", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Experiments_Platforms.platform</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, java.lang.String> PLATFORM = createField("platform", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrol.Experiments_Platforms</code> table reference
	 */
	public ExperimentsPlatforms() {
		this("Experiments_Platforms", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Experiments_Platforms</code> table reference
	 */
	public ExperimentsPlatforms(java.lang.String alias) {
		this(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms.EXPERIMENTS_PLATFORMS);
	}

	private ExperimentsPlatforms(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExperimentsPlatforms(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, java.lang.Integer> getIdentity() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.IDENTITY_EXPERIMENTS_PLATFORMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord> getPrimaryKey() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_EXPERIMENTS_PLATFORMS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_EXPERIMENTS_PLATFORMS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.ExperimentsPlatformsRecord, ?>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.PLATFORM_USER, edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.ACTIVE_PLATFORM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms as(java.lang.String alias) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms rename(java.lang.String name) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.ExperimentsPlatforms(name, null);
	}
}
