/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables;


import edu.kit.ipd.crowdcontrol.objectservice.database.model.Crowdcontrol;
import edu.kit.ipd.crowdcontrol.objectservice.database.model.Keys;
import edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records.RatingOptionExperimentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingOptionExperiment extends TableImpl<RatingOptionExperimentRecord> {

	private static final long serialVersionUID = -155963415;

	/**
	 * The reference instance of <code>crowdcontrol.Rating_Option_Experiment</code>
	 */
	public static final RatingOptionExperiment RATING_OPTION_EXPERIMENT = new RatingOptionExperiment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RatingOptionExperimentRecord> getRecordType() {
		return RatingOptionExperimentRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Rating_Option_Experiment.id_Rating_Option_Experiment</code>.
	 */
	public final TableField<RatingOptionExperimentRecord, Integer> ID_RATING_OPTION_EXPERIMENT = createField("id_Rating_Option_Experiment", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Rating_Option_Experiment.name</code>.
	 */
	public final TableField<RatingOptionExperimentRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Rating_Option_Experiment.value</code>.
	 */
	public final TableField<RatingOptionExperimentRecord, Integer> VALUE = createField("value", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>crowdcontrol.Rating_Option_Experiment.experiment</code>.
	 */
	public final TableField<RatingOptionExperimentRecord, Integer> EXPERIMENT = createField("experiment", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrol.Rating_Option_Experiment</code> table reference
	 */
	public RatingOptionExperiment() {
		this("Rating_Option_Experiment", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Rating_Option_Experiment</code> table reference
	 */
	public RatingOptionExperiment(String alias) {
		this(alias, RATING_OPTION_EXPERIMENT);
	}

	private RatingOptionExperiment(String alias, Table<RatingOptionExperimentRecord> aliased) {
		this(alias, aliased, null);
	}

	private RatingOptionExperiment(String alias, Table<RatingOptionExperimentRecord> aliased, Field<?>[] parameters) {
		super(alias, Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RatingOptionExperimentRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RATING_OPTION_EXPERIMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RatingOptionExperimentRecord> getPrimaryKey() {
		return Keys.KEY_RATING_OPTION_EXPERIMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RatingOptionExperimentRecord>> getKeys() {
		return Arrays.<UniqueKey<RatingOptionExperimentRecord>>asList(Keys.KEY_RATING_OPTION_EXPERIMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RatingOptionExperimentRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RatingOptionExperimentRecord, ?>>asList(Keys.RATING_OPTIONS_EXPERIMENT_REFERENCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RatingOptionExperiment as(String alias) {
		return new RatingOptionExperiment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RatingOptionExperiment rename(String name) {
		return new RatingOptionExperiment(name, null);
	}
}
