/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskChooser extends org.jooq.impl.TableImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord> {

	private static final long serialVersionUID = 1344230066;

	/**
	 * The singleton instance of <code>crowdcontrol.Task_Chooser</code>
	 */
	public static final edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser TASK_CHOOSER = new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord> getRecordType() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord.class;
	}

	/**
	 * The column <code>crowdcontrol.Task_Chooser.id_task_chooser</code>.
	 */
	public final org.jooq.TableField<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord, java.lang.String> ID_TASK_CHOOSER = createField("id_task_chooser", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "");

	/**
	 * Create a <code>crowdcontrol.Task_Chooser</code> table reference
	 */
	public TaskChooser() {
		this("Task_Chooser", null);
	}

	/**
	 * Create an aliased <code>crowdcontrol.Task_Chooser</code> table reference
	 */
	public TaskChooser(java.lang.String alias) {
		this(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser.TASK_CHOOSER);
	}

	private TaskChooser(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord> aliased) {
		this(alias, aliased, null);
	}

	private TaskChooser(java.lang.String alias, org.jooq.Table<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, edu.kit.ipd.crowdcontrol.workerservice.database.model.Crowdcontrol.CROWDCONTROL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord> getPrimaryKey() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_TASK_CHOOSER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.TaskChooserRecord>>asList(edu.kit.ipd.crowdcontrol.workerservice.database.model.Keys.KEY_TASK_CHOOSER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser as(java.lang.String alias) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser rename(java.lang.String name) {
		return new edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.TaskChooser(name, null);
	}
}
