/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records;


import edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.AlgorithmAnswerQuality;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlgorithmAnswerQualityRecord extends UpdatableRecordImpl<AlgorithmAnswerQualityRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -720963671;

	/**
	 * Setter for <code>crowdcontrol.Algorithm_Answer_Quality.id_Algorithm_Answer_Quality</code>.
	 */
	public void setIdAlgorithmAnswerQuality(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Algorithm_Answer_Quality.id_Algorithm_Answer_Quality</code>.
	 */
	public String getIdAlgorithmAnswerQuality() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Algorithm_Answer_Quality.description</code>.
	 */
	public void setDescription(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Algorithm_Answer_Quality.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AlgorithmAnswerQuality.ALGORITHM_ANSWER_QUALITY.ID_ALGORITHM_ANSWER_QUALITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AlgorithmAnswerQuality.ALGORITHM_ANSWER_QUALITY.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getIdAlgorithmAnswerQuality();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlgorithmAnswerQualityRecord value1(String value) {
		setIdAlgorithmAnswerQuality(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlgorithmAnswerQualityRecord value2(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlgorithmAnswerQualityRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlgorithmAnswerQualityRecord
	 */
	public AlgorithmAnswerQualityRecord() {
		super(AlgorithmAnswerQuality.ALGORITHM_ANSWER_QUALITY);
	}

	/**
	 * Create a detached, initialised AlgorithmAnswerQualityRecord
	 */
	public AlgorithmAnswerQualityRecord(String idAlgorithmAnswerQuality, String description) {
		super(AlgorithmAnswerQuality.ALGORITHM_ANSWER_QUALITY);

		setValue(0, idAlgorithmAnswerQuality);
		setValue(1, description);
	}
}
