/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.records;


import edu.kit.ipd.crowdcontrol.objectservice.database.model.tables.Answer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerRecord extends UpdatableRecordImpl<AnswerRecord> implements Record10<Integer, Integer, String, Timestamp, Integer, Integer, Integer, Boolean, String, Long> {

	private static final long serialVersionUID = 1776031983;

	/**
	 * Setter for <code>crowdcontrol.Answer.id_answer</code>.
	 */
	public void setIdAnswer(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.id_answer</code>.
	 */
	public Integer getIdAnswer() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.experiment</code>.
	 */
	public void setExperiment(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.experiment</code>.
	 */
	public Integer getExperiment() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.answer</code>.
	 */
	public void setAnswer(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.answer</code>.
	 */
	public String getAnswer() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.timestamp</code>.
	 */
	public void setTimestamp(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.timestamp</code>.
	 */
	public Timestamp getTimestamp() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.worker_id</code>.
	 */
	public void setWorkerId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.worker_id</code>.
	 */
	public Integer getWorkerId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.reservation</code>.
	 */
	public void setReservation(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.reservation</code>.
	 */
	public Integer getReservation() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.quality</code>.
	 */
	public void setQuality(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.quality</code>.
	 */
	public Integer getQuality() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.quality_assured</code>.
	 */
	public void setQualityAssured(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.quality_assured</code>.
	 */
	public Boolean getQualityAssured() {
		return (Boolean) getValue(7);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.system_response</code>.
	 */
	public void setSystemResponse(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.system_response</code>.
	 */
	public String getSystemResponse() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>crowdcontrol.Answer.hash</code>.
	 */
	public void setHash(Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answer.hash</code>.
	 */
	public Long getHash() {
		return (Long) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Timestamp, Integer, Integer, Integer, Boolean, String, Long> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Timestamp, Integer, Integer, Integer, Boolean, String, Long> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Answer.ANSWER.ID_ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Answer.ANSWER.EXPERIMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Answer.ANSWER.ANSWER_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Answer.ANSWER.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Answer.ANSWER.WORKER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Answer.ANSWER.RESERVATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Answer.ANSWER.QUALITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return Answer.ANSWER.QUALITY_ASSURED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Answer.ANSWER.SYSTEM_RESPONSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field10() {
		return Answer.ANSWER.HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getExperiment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getWorkerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getReservation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getQuality();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getQualityAssured();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSystemResponse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value10() {
		return getHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value1(Integer value) {
		setIdAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value2(Integer value) {
		setExperiment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value3(String value) {
		setAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value4(Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value5(Integer value) {
		setWorkerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value6(Integer value) {
		setReservation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value7(Integer value) {
		setQuality(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value8(Boolean value) {
		setQualityAssured(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value9(String value) {
		setSystemResponse(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord value10(Long value) {
		setHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswerRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Integer value5, Integer value6, Integer value7, Boolean value8, String value9, Long value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnswerRecord
	 */
	public AnswerRecord() {
		super(Answer.ANSWER);
	}

	/**
	 * Create a detached, initialised AnswerRecord
	 */
	public AnswerRecord(Integer idAnswer, Integer experiment, String answer, Timestamp timestamp, Integer workerId, Integer reservation, Integer quality, Boolean qualityAssured, String systemResponse, Long hash) {
		super(Answer.ANSWER);

		setValue(0, idAnswer);
		setValue(1, experiment);
		setValue(2, answer);
		setValue(3, timestamp);
		setValue(4, workerId);
		setValue(5, reservation);
		setValue(6, quality);
		setValue(7, qualityAssured);
		setValue(8, systemResponse);
		setValue(9, hash);
	}
}
