/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationReceiverEmailRecord extends org.jooq.impl.UpdatableRecordImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.NotificationReceiverEmailRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1554183636;

	/**
	 * Setter for <code>crowdcontrol.Notification_Receiver_Email.id_notification_receiver_email</code>.
	 */
	public void setIdNotificationReceiverEmail(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Notification_Receiver_Email.id_notification_receiver_email</code>.
	 */
	public java.lang.Integer getIdNotificationReceiverEmail() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Notification_Receiver_Email.notification</code>.
	 */
	public void setNotification(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Notification_Receiver_Email.notification</code>.
	 */
	public java.lang.Integer getNotification() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Notification_Receiver_Email.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Notification_Receiver_Email.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.NotificationReceiverEmail.NOTIFICATION_RECEIVER_EMAIL.ID_NOTIFICATION_RECEIVER_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.NotificationReceiverEmail.NOTIFICATION_RECEIVER_EMAIL.NOTIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.NotificationReceiverEmail.NOTIFICATION_RECEIVER_EMAIL.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdNotificationReceiverEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNotification();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationReceiverEmailRecord value1(java.lang.Integer value) {
		setIdNotificationReceiverEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationReceiverEmailRecord value2(java.lang.Integer value) {
		setNotification(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationReceiverEmailRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationReceiverEmailRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotificationReceiverEmailRecord
	 */
	public NotificationReceiverEmailRecord() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.NotificationReceiverEmail.NOTIFICATION_RECEIVER_EMAIL);
	}

	/**
	 * Create a detached, initialised NotificationReceiverEmailRecord
	 */
	public NotificationReceiverEmailRecord(java.lang.Integer idNotificationReceiverEmail, java.lang.Integer notification, java.lang.String email) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.NotificationReceiverEmail.NOTIFICATION_RECEIVER_EMAIL);

		setValue(0, idNotificationReceiverEmail);
		setValue(1, notification);
		setValue(2, email);
	}
}
