/**
 * This class is generated by jOOQ
 */
package edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerBalanceRecord extends org.jooq.impl.UpdatableRecordImpl<edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.records.WorkerBalanceRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType, java.sql.Timestamp> {

	private static final long serialVersionUID = 1683290849;

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.id_worker_balance</code>.
	 */
	public void setIdWorkerBalance(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.id_worker_balance</code>.
	 */
	public java.lang.Integer getIdWorkerBalance() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.transaction_value</code>.
	 */
	public void setTransactionValue(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.transaction_value</code>.
	 */
	public java.lang.Integer getTransactionValue() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.worker</code>.
	 */
	public void setWorker(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.worker</code>.
	 */
	public java.lang.Integer getWorker() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.experiment</code>.
	 */
	public void setExperiment(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.experiment</code>.
	 */
	public java.lang.Integer getExperiment() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.gift_code</code>.
	 */
	public void setGiftCode(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.gift_code</code>.
	 */
	public java.lang.Integer getGiftCode() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.type</code>.
	 */
	public void setType(edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.type</code>.
	 */
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType getType() {
		return (edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType) getValue(5);
	}

	/**
	 * Setter for <code>crowdcontrol.Worker_Balance.timestamp</code>.
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Worker_Balance.timestamp</code>.
	 */
	public java.sql.Timestamp getTimestamp() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.ID_WORKER_BALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.TRANSACTION_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.WORKER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.EXPERIMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.GIFT_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType> field6() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdWorkerBalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTransactionValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getWorker();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getExperiment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getGiftCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType value6() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value1(java.lang.Integer value) {
		setIdWorkerBalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value2(java.lang.Integer value) {
		setTransactionValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value3(java.lang.Integer value) {
		setWorker(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value4(java.lang.Integer value) {
		setExperiment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value5(java.lang.Integer value) {
		setGiftCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value6(edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord value7(java.sql.Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkerBalanceRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkerBalanceRecord
	 */
	public WorkerBalanceRecord() {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE);
	}

	/**
	 * Create a detached, initialised WorkerBalanceRecord
	 */
	public WorkerBalanceRecord(java.lang.Integer idWorkerBalance, java.lang.Integer transactionValue, java.lang.Integer worker, java.lang.Integer experiment, java.lang.Integer giftCode, edu.kit.ipd.crowdcontrol.workerservice.database.model.enums.WorkerBalanceType type, java.sql.Timestamp timestamp) {
		super(edu.kit.ipd.crowdcontrol.workerservice.database.model.tables.WorkerBalance.WORKER_BALANCE);

		setValue(0, idWorkerBalance);
		setValue(1, transactionValue);
		setValue(2, worker);
		setValue(3, experiment);
		setValue(4, giftCode);
		setValue(5, type);
		setValue(6, timestamp);
	}
}
