/**
 * This class is generated by jOOQ
 */
package edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswersRecord extends org.jooq.impl.UpdatableRecordImpl<edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.records.AnswersRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = -65093555;

	/**
	 * Setter for <code>crowdcontrol.Answers.idAnswers</code>.
	 */
	public void setIdanswers(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answers.idAnswers</code>.
	 */
	public java.lang.Integer getIdanswers() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crowdcontrol.Answers.task</code>.
	 */
	public void setTask(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answers.task</code>.
	 */
	public java.lang.Integer getTask() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>crowdcontrol.Answers.answer</code>.
	 */
	public void setAnswer(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answers.answer</code>.
	 */
	public java.lang.String getAnswer() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>crowdcontrol.Answers.timestamp</code>.
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answers.timestamp</code>.
	 */
	public java.sql.Timestamp getTimestamp() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>crowdcontrol.Answers.worker_id</code>.
	 */
	public void setWorkerId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>crowdcontrol.Answers.worker_id</code>.
	 */
	public java.lang.Integer getWorkerId() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS.IDANSWERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS.TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS.ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS.WORKER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdanswers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTask();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getWorkerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord value1(java.lang.Integer value) {
		setIdanswers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord value2(java.lang.Integer value) {
		setTask(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord value3(java.lang.String value) {
		setAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord value4(java.sql.Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord value5(java.lang.Integer value) {
		setWorkerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnswersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnswersRecord
	 */
	public AnswersRecord() {
		super(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS);
	}

	/**
	 * Create a detached, initialised AnswersRecord
	 */
	public AnswersRecord(java.lang.Integer idanswers, java.lang.Integer task, java.lang.String answer, java.sql.Timestamp timestamp, java.lang.Integer workerId) {
		super(edu.ipd.kit.crowdcontrol.workerservice.database.model.tables.Answers.ANSWERS);

		setValue(0, idanswers);
		setValue(1, task);
		setValue(2, answer);
		setValue(3, timestamp);
		setValue(4, workerId);
	}
}
